### ISSUE TITLE
Virtual Environment has been pushed

### ISSUE THREAD

**Issue by nachiketbhuta** [alisolanki/startup#3]
1. It is a better practice to add your virtual environment in the .gitignore file because virtual environment can increase the size of the project on GitHub. 
2. Just add the dependencies of the virtual environment to ```requirements.txt``` in the root of the project by using ```pip freeze > requirements.txt``` where ```manage.py``` file exists.
3. So that if anyone has to install the dependencies of the project, then they can create their own virtual environment and install the dependencies from the ```requirements.txt```.
4. @alisolanki Do the above changes and you are good to go. 

Happy Coding!! :)

**Comment by alisolanki** [comment]
Thank you @nachiketbhuta . I'd make those changes.
